config/routes.rb
TwitterClone::Application.routes.draw do
  root 'epicenter#feed'

  get "user_profile" => "epicenter#show_user"
  post "now_following" => "epicenter#now_following"
  post "unfollow" => "epicenter#unfollow"

  resources :tweets

  devise_for :users

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	validates :message, presence: true
	validates :message, length: {maximum: 140, too_long: "A tweet is only 140 characters."}
	
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true

  serialize :following, Array

  has_many :tweets


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
      :name, :username, :bio, :location, :following, :latitude, :longitude) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
      :current_password, :name, :username, :bio, :location, :following, :latitude, :longitude) }
   end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
  	#initialize the array that will hold tweets
  	#from the current_user's following list.
  	@following_tweets = []
  	#pull in all the tweets
  	@tweets = Tweet.all
  	@users = User.all

  	@follower_count = 0
  	#then we sort through the tweets
  	#find the ones associated with users from
  	#current_user's following array
  	if user_signed_in?
	  	@tweets.each do |tweet|
	  		current_user.following.each do |f|
	  			if tweet.user_id == f
	  				@following_tweets.push(tweet)
	  			#those tweets are pushed into the
	  			#array we called in the view
	  			end
	  		end
	  	end
	  	@users.each do |user|
	  		if user.following.include?(current_user.id)
	  			@follower_count += 1
	  		end
	  	end
	else
		redirect_to new_user_session_path
	end
  end

  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
  	@user = User.find(params[:follow_id])
  	current_user.following.push(params[:follow_id].to_i)
  	#adding user.id of the user you want to follow to your 'following' attr
  	current_user.save
  	#then save in database
  	redirect_to user_profile_path(id: @user.id)
  end

  def unfollow
  	@user = User.find(params[:unfollow_id])
  	current_user.following.delete(params[:unfollow_id].to_i)
  	#removing user.id of the user you want to unfollow from your 'following' attr
  	current_user.save
  	redirect_to tweets_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  respond_to :html

  def index
    @tweets = Tweet.all
    respond_with(@tweets)
  end

  def show
    respond_with(@tweet)
  end

  def new
    @tweet = Tweet.new
    respond_with(@tweet)
  end

  def edit
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.save
    respond_with(@tweet)
  end

  def update
    @tweet.update(tweet_params)
    respond_with(@tweet)
  end

  def destroy
    @tweet.destroy
    respond_with(@tweet)
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/epicenter/feed.html.erb
<div class="panel panel-default">
	<div class="panel body">
		<h1>Twitter Feed</h1>
		<p>Here is what your friends are saying:</p>
	</div>
</div>
<div class="row">
	<div class="current-user-profile-box col-md-4 panel panel-default">
		<div class="panel-body">
			<div class="row">
				<h3><%= current_user.name %></h3>
				<p><%= current_user.username %></p>
			</div>
			<div class="row">
				<div class="col-md-4">
					<span class="small-text">TWEETS</span><br />
					<%= current_user.tweets.count %>
				</div>
				<div class="col-md-4">
					<span class="small-text">FOLLOWING</span><br />
					<%= current_user.following.length %>
				</div>
				<div class="col-md-4">
					<span class="small-text">FOLLOWERS</span><br />
					<%= @follower_count %>
				</div>
			</div>
		</div>
	</div>
	<div class="following-feed-box col-md-7 col-md-offset-1 panel panel-default">
		<div class="panel-body">
			<% @following_tweets.each do |tweet| %>
				<p>
					<strong><%= link_to tweet.user.username, user_profile_path(id: tweet.user.id) %>:</strong><br />
					<%= tweet.message %>
				</p>
			<% end %>
		</div>
	</div>
</div>



	

app/views/epicenter/now_following.html.erb
<p>You are now following: <%= @user.username %></p>

app/views/epicenter/show_user.html.erb
<div class="show_user">	
	<h1><%= @user.username %></h1>
	<h3><%= @user.location %></h3>
	<h3><%= @user.latitude %></h3>
	<h3><%= @user.longitude %></h3>
	<h3><%= @user.bio %></h3>

	<div class="row">
		<% @user.tweets.each do |tweet| %>
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-body">
					<p><%= tweet.message %></p>
				</div>
			</div>
		</div>
		<% end %>
	</div>
	<div class="row">
		<div class="col-md-4"> 
			<% if current_user.id != @user.id %>
				<% if current_user.following.include?(@user.id) %>
					<%= form_tag('/unfollow') do %>
						<div hidden>
							<%= text_field_tag :unfollow_id, @user.id %>
						</div>
						<%= submit_tag 'Following', class: 'btn btn-primary', id: 'unfollow_btn' %>
					<% end %>
				<% else %>
				<div>
					<%= form_tag('/now_following') do %>
					<div hidden>
						<%= text_field_tag :follow_id, @user.id %>
					</div><br />
					<%= submit_tag 'Follow', class: 'btn btn-primary', id: 'follow_btn' %>
					<% end %>
				</div>
				<% end %>
			<% end %>
		</div>
		<div class="col-md-8"> 
			<div id="map-canvas"></div>
		</div>
	</div>
</div>


<script>
	$(document).ready(function(){
		$('#unfollow_btn').hover(function(){
			$(this).removeClass("btn-primary");
			$(this).addClass("btn-danger");
			$(this).attr('value', 'Unfollow');
		}, 	function() {
			$(this).attr('value', 'Following');
			$(this).removeClass("btn-danger");
			$(this).addClass("btn-primary");
		});
	});
</script>

<script>
	$(document).ready(function(){
		$('#follow_btn').hover(function(){
			$(this).removeClass("btn-primary");
			$(this).addClass("btn-success");
			$(this).attr('value', 'Follow');
		}, 	function() {
			$(this).attr('value', 'Follow');
			$(this).removeClass("btn-success");
			$(this).addClass("btn-primary");
		});
	});
</script>

app/views/epicenter/unfollow.html.erb
<p>You are no longer following: <%= @user.username %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>Twitter Clone</title>
	  	<!-- Latest compiled and minified CSS -->
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

		<!-- Optional theme -->
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

		<!-- Latest compiled and minified JavaScript -->
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

	  <script type="text/javascript"
      	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCnsBKjiAcGKYchCvq6KMZDypX5dbbWTzo">
 	  </script>


	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<% if user_signed_in? %>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
					<%= link_to "Tweets", tweets_path, class: "navbar-brand"%>
					<%= link_to "My Feed", root_path, class: "navbar-brand"%>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-left">
						<!-- Future links-->
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
						<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
					</ul>
				</div>
			</div>
		</nav>
		<% else %>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
					<%= link_to "Tweets", tweets_path, class: "navbar-brand"%>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "Sign Up", new_user_registration_path %></li>
						<li><%= link_to "Forgot Password", new_user_password_path %></li>
					</ul>
				</div>
			</div>
		</nav>
		<% end %>
		<% if flash[:notice] %>
       <div class="notice"><%= flash[:notice] %></div>
  		<% end %>
		<% if flash[:alert] %>
       <div class="alert"><%= flash[:alert] %></div>
  		<% end %>
		<%= yield %>
	</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :message %>
  </div>
  <div class="field" hidden>
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Tweet!", class: "btn btn-info" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="edit_tweet">	
	<h1>Editing tweet</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="tweets-page">
  <h1>Listing tweets</h1>

  <table>
    <thead>
      <tr>
        <th>Message</th>
        <th>User</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet.message %></td>
          <td><%= link_to tweet.user.username, user_profile_path(id: tweet.user.id) %></td>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Tweet!', new_tweet_path, class: "btn btn-info" %>
</div>

app/views/tweets/new.html.erb
<div class="new_tweet">
	<h1>New tweet</h1>

	<%= render 'form' %>

	<%= link_to 'Back', tweets_path, class: "btn" %>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, user_profile_path(id: @tweet.user.id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>